apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
    - name: service1
      port: 7650
      targetPort: 7650
      protocol: TCP
    - name: service2
      port: 7651
      targetPort: 7651
      protocol: TCP
    - name: service3
      port: 7653
      targetPort: 7653
      protocol: TCP
    - name: service4
      port: 7659
      targetPort: 7659
      protocol: TCP
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      volumes:
        - name: oklog-configmap
          configMap:
            name: {{ template "fullname" . }}-cm
      containers:
        - name: oklog
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /bin/sh
            - /go/bin/start.sh
          volumeMounts:
            #  - name: export
            #    mountPath: /data
            - name: oklog-configmap
              mountPath: /go/bin/start.sh
              subPath: start.sh
          ports:
            - name: service1
              containerPort: 7650
            - name: service2
              containerPort: 7651
            - name: service3
              containerPort: 7653
            - name: service4
              containerPort: 7659
          resources:
{{ toYaml .Values.resources | indent 12}}
  #volumeClaimTemplates:
  #  - metadata:
  #      name: export
  #      annotations:
  #        {{- if .Values.persistence.storageClass }}
  #        volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
  #        {{- else }}
  #        volume.alpha.kubernetes.io/storage-class: default
  #        {{- end }}
  #    spec:
  #      accessModes: [ {{ .Values.persistence.accessMode | quote }} ]
  #      resources:
  #        requests:
  #          storage: {{ .Values.persistence.size }}
