# Inspired by https://github.com/kubernetes/charts/blob/master/stable/minio/values.yaml

# Docker image
image: "oklog/oklog"
imageTag: v0.2.0
imagePullPolicy: "Always"

replicas: 4
persistence:
  accessMode: ReadWriteOnce
  size: 1Gi

serviceType: LoadBalancer
servicePort: 3000

# Configure
resources:
  requests:
    memory: 256Mi
    cpu: 250m
